# Generated by Django 5.1 on 2024-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_login_id_remove_login_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='reg_id',
        ),
        migrations.AddField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
