# Generated by Django 5.1 on 2024-08-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_login_reg_id_remove_register_reg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='log',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reg'),
        ),
    ]
