# Generated by Django 5.1.3 on 2025-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('post_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('price', models.IntegerField(default=15)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
